package com.etachi.smartassetmanagement.ui.assets

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.core.widget.addTextChangedListener
import androidx.fragment.app.Fragment
import androidx.fragment.app.activityViewModels
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.lifecycleScope
import androidx.lifecycle.repeatOnLifecycle
import androidx.navigation.fragment.findNavController
import androidx.navigation.fragment.navArgs
import androidx.recyclerview.widget.LinearLayoutManager
import com.etachi.smartassetmanagement.databinding.FragmentAssetsBinding
import com.etachi.smartassetmanagement.domain.model.Permission
import com.etachi.smartassetmanagement.ui.list.AssetAdapter
import com.etachi.smartassetmanagement.ui.list.AssetViewModel
import com.etachi.smartassetmanagement.utils.UserSessionManager
import com.etachi.smartassetmanagement.utils.showIfHasPermission
import dagger.hilt.android.AndroidEntryPoint
import kotlinx.coroutines.flow.collectLatest
import kotlinx.coroutines.launch
import javax.inject.Inject

@AndroidEntryPoint
class AssetsFragment : Fragment() {

    private var _binding: FragmentAssetsBinding? = null
    private val binding get() = _binding!!

    // Shared ViewModel (Activity scope so it persists across tabs)
    private val viewModel: AssetViewModel by activityViewModels()

    private lateinit var adapter: AssetAdapter

    @Inject
    lateinit var sessionManager: UserSessionManager

    // ✅ Safe Args to receive roomId from Organigram
    // FIX #3: AssetsFragmentArgs is generated by Safe Args plugin.
    // Make sure your nav_graph.xml has a <argument android:name="roomId"> inside <fragment id="assetsFragment">
    // AND the Safe Args Gradle plugin is applied in your build.gradle
    private val args: AssetsFragmentArgs by navArgs()

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentAssetsBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        // ✅ STEP 1: Apply Room Filter if coming from Organigram
        val roomId = args.roomId
        if (!roomId.isNullOrBlank()) {
            viewModel.setRoomFilter(roomId)
        }

        setupRecyclerView()
        setupListeners()
        observeData()
    }

    private fun setupRecyclerView() {
        adapter = AssetAdapter { asset ->
            try {
                val action = AssetsFragmentDirections.actionAssetsFragmentToAssetDetailFragment(asset.id) // ✅ added "Fragment"
                findNavController().navigate(action)
            } catch (e: Exception) {
                // Silently fail if user clicks too fast
            }
        }

        binding.recyclerViewAssets.layoutManager = LinearLayoutManager(requireContext())
        binding.recyclerViewAssets.adapter = adapter
    }

    private fun setupListeners() {
        // SECURITY ENFORCEMENT: Hide FAB if no permission
        // FIX #2: Corrected typo from "ASCSET_CREATE" → "ASSET_CREATE"
        binding.fabAdd.showIfHasPermission(sessionManager, Permission.ASSET_CREATE)

        binding.fabAdd.setOnClickListener {
            // ✅ STEP 2: Clear the filter when creating a new asset
            viewModel.setRoomFilter(null)

            // FIX #4: Uses AssetsFragmentDirections (generated by Safe Args)
            val action = AssetsFragmentDirections.actionAssetsFragmentToAddAssetFragment()
            findNavController().navigate(action)
        }

        // FIX #1: Added the missing closing parenthesis ')' after the lambda '}'
        binding.editTextSearch.addTextChangedListener(afterTextChanged = { editable ->
            viewModel.setSearchQuery(editable.toString())
        })
    }

    private fun observeData() {
        viewLifecycleOwner.lifecycleScope.launch {
            viewLifecycleOwner.repeatOnLifecycle(Lifecycle.State.STARTED) {
                viewModel.assets.collectLatest { assetList ->
                    adapter.submitList(assetList)
                    binding.emptyStateView.visibility =
                        if (assetList.isEmpty()) View.VISIBLE else View.GONE
                }
            }
        }
    }

    override fun onDestroyView() {
        super.onDestroyView()
        // ✅ STEP 3: Clear room filter when leaving the screen
        viewModel.setRoomFilter(null)
        _binding = null
    }
}